run script now works

diff --git a/infra/images/staging/ws/bin/run b/infra/images/staging/ws/bin/run
--- a/infra/images/staging/ws/bin/run
+++ b/infra/images/staging/ws/bin/run
@@ -1,44 +1,63 @@
 #! /bin/bash
 
-# Constants
-IMAGE_TAG="dev"
-IMAGE_NAME="gophr-ws"
-CONTAINER_NAME="gophr-ws"
-API_CONTAINER_NAME="gophr-api"
-ROUTER_CONTAINER_NAME="gophr-router"
-DOCKER_MACHINE_NAME="gophr-dev"
-
-# Get base directories
-bin_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-image_dir="$( dirname $bin_dir )"
-project_dir="$( dirname $( dirname $( dirname $( dirname $image_dir ) ) ) )"
-
 # Color variables
 esc_seq="\x1b["
 no_color=$esc_seq"39;49;00m"
+red_color=$esc_seq"31;01m"
 green_color=$esc_seq"32;01m"
 
-# Start the docker machine
-echo "Starting the docker machine..."
-docker-machine start $DOCKER_MACHINE_NAME &>/dev/null
-echo -e "${green_color}✓ Docker machine started successfully!${no_color}"
+# Constants
+IMAGE_TAG="staging"
+IMAGE_NAME="gophr-ws"
+CLUSTER_NAME="gophr-staging"
+DOCKER_MACHINE_NAME="gophr-staging"
 
-# Connect to the docker machine
-echo "Connecting to the docker machine..."
-eval $(docker-machine env "$DOCKER_MACHINE_NAME")
-echo -e "${green_color}✓ Connected to the docker machine successfully!${no_color}"
+# Get base directories
+bin_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+config_dir="$( dirname $bin_dir )/config"
+staging_bin_dir="$( dirname $( dirname $( dirname $( dirname $bin_dir ) ) ) )/bin/staging"
 
-# Kill the existing container
-$bin_dir/kill
+# Runtime flags
+cluster_exposed="false"
 
-echo "Starting '$IMAGE_NAME:$IMAGE_TAG' container..."
-docker run \
-  -d \
-  -p 80:80 \
-  -p 443:443 \
-  -v "$project_dir/web/dist":/usr/share/nginx/html:ro \
-  --name "$CONTAINER_NAME" \
-  --link "$API_CONTAINER_NAME:$API_CONTAINER_NAME" \
-  --link "$ROUTER_CONTAINER_NAME:$ROUTER_CONTAINER_NAME" \
-  "$IMAGE_NAME:$IMAGE_TAG" && \
-echo -e "${green_color}✓ The '$IMAGE_NAME:$IMAGE_TAG' container was started successfully!${no_color}"
+# Create an exit hook
+on_premature_exit() {
+  if [[ "$?" -ne "0" ]]; then
+    echo -e "${red_color}✗ Failed to deploy '$IMAGE_NAME:$IMAGE_TAG'.${no_color}"
+  fi
+
+  # Unexpose the cluster
+  if [[ "$cluster_exposed" -eq "true" ]]; then
+    "${staging_bin_dir}/unexpose" &> /dev/null || true
+  fi
+}
+
+# Setup the exit hook
+trap 'on_premature_exit' EXIT
+
+# Exit on error
+set -e
+
+# Ensure kubectl is pointing to the right thing
+echo "Connecting to cluster '${CLUSTER_NAME}'..."
+kubectl config use-context ${CLUSTER_NAME}
+"${staging_bin_dir}/expose" &> /dev/null || true
+cluster_exposed="true"
+echo -e "${green_color}✓ Connected to the cluster successfully!${no_color}"
+
+echo "Disabling old kubernetes config..."
+kubectl delete -f "$config_dir/svc.yaml" &> /dev/null || true
+kubectl delete -f "$config_dir/rc.yaml" &> /dev/null || true
+echo -e "${green_color}✓ Old kubernetes config disabled successfully!${no_color}"
+
+echo "Applying updated kubernetes config..."
+echo "$config_dir/pod.yaml"
+kubectl create -f "$config_dir/rc.yaml"
+kubectl create -f "$config_dir/svc.yaml"
+echo -e "${green_color}✓ Updated kubernetes config applied successfully!${no_color}"
+
+echo "Disconnecting from cluster '${CLUSTER_NAME}'..."
+"${staging_bin_dir}/unexpose" &> /dev/null || true
+cluster_exposed="false"
+
+echo -e "${green_color}✓ The '$IMAGE_NAME:$IMAGE_TAG' was deployed successfully!${no_color}"
